### ISSUE TITLE
Airport Health Laboratory issues - LIMS

### ISSUE THREAD

**Issue by AirportMauritius** [I-TECH-UW/OpenELIS-Global-2#201]
Dear Sir/Madam,

                                                                    Subject: LIMS - Gap in number labels
 1) Since the start of LIMS use in AHL, there have been multiple instances when, printing barcodes labels to be used on sample tubes, there were gaps between end number of one batch start umber of the following batch of barcode labels.

2) The gaps were between 10 to 15 numbers skipped. As replacement, AHL staff had to manually write on blank labels to ensure continuity of sample numbering.

3) On Monday 11/01/2021, the gap had suddenly increased to 1200. The existing stock of barcode labels ends on 10515 when displaying a Print Preview of barcodes to be printed through LIMS, the next immediate batch of barcode labels started with 11725 

4)  The importance of continuity in the numbering of samples for AHL lies in the fact that the last barcode number used for the day's shift corresponds to the total number of samples processed since the start of AHL operations

Regards,

AHL Team

**Comment by caseyi** [comment]
Hi all, 

Thank you for this report. OpenELIS is designed to avoid at all costs the duplication of accession numbers since this would be a critical problem and would break the ability to identify a sample. It's likely that these gaps were created by the system generating batches of pre-printed barcodes, that were not printed, or created accidentally. To help give an alternative to the automatic generation provided by OpenELIS, we have made a feature that will allow any number to be scanned into the recession number on the order entry screen, as long as it is not already in the system. This should allow the use of commercially pre-printed barcodes or those made with barcode generation software. This will allow you to ensure that there are no skipped numbers to fit your preferred workflow. The option to change is in Admin - Order Entry Configuration -> Validate accession numbers, and set this to False. 

Please let me know if you have questions. 

Regards, 
OE Team
